version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailstorm-backend
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      POSTGRES_DB: tailstorm_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/tailstorm_dev
      SECRET_KEY: your-local-secret-key
      DEBUG: "true"
      ENV: development
      API_URL: http://localhost:8000
      ALLOWED_HOSTS: localhost,127.0.0.1
    depends_on:
      - db
    volumes:
      - .:/app
      - ./client:/app/client
      - ./backend:/app/backend

  db:
    image: postgres:15
    container_name: tailstorm-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tailstorm_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
